name: Unit Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'Lab 4/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Lab 4/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # specify your Node.js version

      - name: Set Permissions
        run: chmod -R 755 ./Lab 4

      - name: Install Dependencies
        run: npm install
        working-directory: ./Lab 4

      - name: Unit Test
        run: npm test
        working-directory: ./Lab 4
